application: startr-endpoint
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

skip_files:
- README.md